version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${TYPEORM_USERNAME}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
    ports:
      - ${TYPEORM_PORT}:3306
